version: "3"
services:
  api:
    build:
      context: ./ApiCube
      dockerfile: Dockerfile
    ports:
      - "7032:7032"
    restart: always
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql://root:123@db:3306/cubeDatabase

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    restart: always

  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: cubeDatabase
      MYSQL_USER: admim
      MYSQL_PASSWORD: admin
    volumes:
      - db-data:/var/lib/mysql
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: your_root_password
    restart: always
    depends_on:
      - db

volumes:
  db-data:
# network: ressources_relationnelles_default
