FROM node:18.16.0 as build

# Définir le répertoire de travail dans le conteneur
WORKDIR /app

# Copier le fichier package.json et package-lock.json dans le conteneur
COPY package*.json ./

# Installer les dépendances du projet
RUN npm install

# Copier tout le contenu du répertoire actuel dans le conteneur
COPY . .

# Construire l'application Angular
RUN npm install -g @angular/cli@latest
RUN ng build --configuration=production

# Étape suivante : Utiliser un serveur HTTP léger pour servir l'application Angular
FROM nginx:alpine

# Copier les fichiers de build de l'application dans le répertoire de base du serveur Nginx
COPY --from=build /app/dist/front /usr/share/nginx/html/

COPY default.conf /etc/nginx/conf.d/default.conf

# Exposer le port 80 pour accéder à l'application
# EXPOSE 4200

# Commande par défaut pour démarrer le serveur Nginx
CMD ["nginx", "-g", "daemon off;"]
