# Étape 1 : Utiliser une image de base contenant Node.js
FROM node:18.16.0 as build

# Étape 2 : Définir le répertoire de travail dans le conteneur
WORKDIR /app

# Étape 3 : Copier le fichier package.json et package-lock.json dans le conteneur
COPY package*.json ./

# Étape 4 : Installer les dépendances du projet
RUN npm install

# Étape 5 : Copier tout le contenu du répertoire actuel dans le conteneur
COPY . .

# Étape 6 : Construire l'application Angular
RUN npm install -g @angular/cli@latest
RUN ng build

# Étape 7 : Utiliser une image de base légère pour la production
# FROM nginx:1.21.0-alpine

# Étape 8 : Copier les fichiers de l'application Angular dans le répertoire de l'image nginx
# COPY --from=build /app/dist/re /usr/share/nginx/html

# Étape 9 : Exposer le port 80 pour accéder à l'application
EXPOSE 80

# Étape 10 : Démarrer le serveur NGINX lors de l'exécution du conteneur
# CMD ["nginx", "-g", "daemon off;"]